In [1]:
#db 연결 코드
import sqlite3

conn = sqlite3.connect('./data/flights.db')
cur = conn.cursor()
cur.execute('select * from airlines limit 5;')
results = cur.fetchall()
results

[(0, '1', 'Private flight', '\\N', '-', None, None, None, 'Y'),
 (1, '2', '135 Airways', '\\N', None, 'GNL', 'GENERAL', 'United States', 'N'),
 (2, '3', '1Time Airline', '\\N', '1T', 'RNX', 'NEXTIME', 'South Africa', 'Y'),
 (3,
  '4',
  '2 Sqn No 1 Elementary Flying Training School',
  '\\N',
  None,
  'WYT',
  None,
  'United Kingdom',
  'N'),
 (4, '5', '213 Flight Unit', '\\N', None, 'TFU', None, 'Russia', 'N')]

In [4]:
import pandas as pd

In [9]:
df_airplines = pd.read_sql_query('select * from airlines;', conn)
df_airports = pd.read_sql_query('select * from airports;',conn)
df_routes = pd.read_sql_query('select * from routes;', conn)

In [11]:
df_airplines

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N
5,5,6,223 Flight Unit State Airline,\N,None,CHD,CHKALOVSK-AVIA,Russia,N
6,6,7,224th Flight Unit,\N,None,TTF,CARGO UNIT,Russia,N
7,7,8,247 Jet Ltd,\N,None,TWF,CLOUD RUNNER,United Kingdom,N
8,8,9,3D Aviation,\N,None,SEC,SECUREX,United States,N
9,9,10,40-Mile Air,\N,Q5,MLA,MILE-AIR,United States,Y
10,10,11,4D Air,\N,None,QRT,QUARTET,Thailand,N
11,11,12,611897 Alberta Limited,\N,None,THD,DONUT,Canada,N
12,12,13,Ansett Australia,\N,AN,AAA,ANSETT,Australia,Y
13,13,14,Abacus International,\N,1B,None,None,Singapore,Y
14,14,15,Abelag Aviation,\N,W9,AAB,ABG,Belgium,N
15,15,16,Army Air Corps,\N,None,AAC,ARMYAIR,United Kingdom,N
16,16,17,Aero Aviation Centre Ltd.,\N,None,AAD,SUNRISE,Canada,N
17,17,18,Aero Servicios Ejecutivos Internacionales,\N,None,SII,ASEISA,Mexico,N
18,18,19,Aero Biniza,\N,None,BZS,BINIZA,Mexico,N
19,19,20,Aero Albatros,\N,None,ABM,ALBATROS ESPANA,Spain,N
20,20,21,Aigle Azur,\N,ZI,AAF,AIGLE AZUR,France,Y
21,21,22,Aloha Airlines,\N,AQ,AAH,ALOHA,United States,Y
22,22,23,Alaska Island Air,\N,None,AAK,ALASKA ISLAND,United States,N
23,23,24,American Airlines,\N,AA,AAL,AMERICAN,United States,Y
24,24,25,Aviation Management Corporation,\N,None,AAM,AM CORP,United States,N
25,25,26,Atlantis Airlines (USA),\N,None,AAO,ATLANTIS AIR,United States,N
26,26,27,Aerovista Airlines,\N,None,AAP,AEROVISTA GROUP,United Arab Emirates,N
27,27,28,Asiana Airlines,\N,OZ,AAR,ASIANA,Republic of Korea,Y
28,28,29,Askari Aviation,\N,4K,AAS,AL-AAS,Pakistan,Y
29,29,30,Australia Asia Airlines,\N,None,AAU,AUSTASIA,Australia,N
...,...,...,...,...,...,...,...,...,...
6018,6018,19651,CARICOM AIRWAYS (BARBADOS) INC.,CARICOM AIRWAYS,None,CCB,None,Barbados,Y
6019,6019,19674,Rainbow Air (RAI),Rainbow Air (RAI),RN,RAB,Rainbow,United States,Y
6020,6020,19675,Rainbow Air Canada,Rainbow Air CAN,RY,RAY,Rainbow CAN,Canada,Y
6021,6021,19676,Rainbow Air Polynesia,Rainbow Air POL,RX,RPO,Rainbow Air,United States,Y
6022,6022,19677,Rainbow Air Euro,Rainbow Air EU,RU,RUE,Rainbow Air,United Kingdom,Y
6023,6023,19678,Rainbow Air US,Rainbow Air US,RM,RNY,Rainbow Air,United States,Y
6024,6024,19745,Transilvania,None,None,TNS,None,Romania,Y
6025,6025,19751,Dobrolet,Добролёт,QD,DOB,DOBROLET,Russia,Y
6026,6026,19774,Spike Airlines,Aero Spike,S0,SAL,Spike Air,United States,Y
6027,6027,19776,Grand Cru Airlines,None,None,GCA,None,Lithuania,Y
6028,6028,19785,Go2Sky,None,None,RLX,RELAX,Slovakia,Y
6029,6029,19803,All Argentina,All Argentina,L1,AL1,None,Argentina,Y
6030,6030,19804,All America,All America,A2,AL2,None,United States,Y
6031,6031,19805,All Asia,All Asia,L9,AL3,None,China,Y
6032,6032,19806,All Africa,All Africa,9A,99F,None,South Africa,Y
6033,6033,19807,Regionalia México,Regionalia México,N4,J88,None,Mexico,Y
6034,6034,19808,All Europe,All Europe,N9,N99,None,United Kingdom,Y
6035,6035,19809,All Spain,All Spain,N7,N77,None,Spain,Y
6036,6036,19810,Regional Air Iceland,Regional Air Iceland,9N,N78,None,Iceland,Y
6037,6037,19811,British Air Ferries,None,??,??!,None,United Kingdom,N
6038,6038,19812,Voestar,Voestar Brasil,8K,K88,None,Brazil,Y
6039,6039,19813,All Colombia,All Colombia,7O,7KK,None,Colombia,Y
6040,6040,19814,Regionalia Uruguay,Regionalia Uruguay,2X,2K2,None,Uruguay,Y
6041,6041,19815,Regionalia Venezuela,Regionalia Venezuela,9X,9XX,None,Venezuela,Y
6042,6042,19827,Regionalia Chile,Regionalia Chile,9J,CR1,None,Chile,Y
6043,6043,19828,Vuela Cuba,Vuela Cuba,6C,6CC,None,Cuba,Y
6044,6044,19830,All Australia,All Australia,88,8K8,None,Australia,Y
6045,6045,19831,Fly Europa,None,ER,RWW,None,Spain,Y
6046,6046,19834,FlyPortugal,None,PO,FPT,FlyPortugal,Portugal,Y
6047,6047,19845,FTI Fluggesellschaft,None,None,FTI,None,Germany,N

In [12]:
df_airports

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
1,1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
2,2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
3,3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
4,4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby
5,5,6,Wewak Intl,Wewak,Papua New Guinea,WWK,AYWK,-3.583828,143.669186,19,10,U,Pacific/Port_Moresby
6,6,7,Narsarsuaq,Narssarssuaq,Greenland,UAK,BGBW,61.160517,-45.425978,112,-3,E,America/Godthab
7,7,8,Nuuk,Godthaab,Greenland,GOH,BGGH,64.190922,-51.678064,283,-3,E,America/Godthab
8,8,9,Sondre Stromfjord,Sondrestrom,Greenland,SFJ,BGSF,67.016969,-50.689325,165,-3,E,America/Godthab
9,9,10,Thule Air Base,Thule,Greenland,THU,BGTL,76.531203,-68.703161,251,-4,E,America/Thule
10,10,11,Akureyri,Akureyri,Iceland,AEY,BIAR,65.659994,-18.072703,6,0,N,Atlantic/Reykjavik
11,11,12,Egilsstadir,Egilsstadir,Iceland,EGS,BIEG,65.283333,-14.401389,76,0,N,Atlantic/Reykjavik
12,12,13,Hornafjordur,Hofn,Iceland,HFN,BIHN,64.295556,-15.227222,24,0,N,Atlantic/Reykjavik
13,13,14,Husavik,Husavik,Iceland,HZK,BIHU,65.952328,-17.425978,48,0,N,Atlantic/Reykjavik
14,14,15,Isafjordur,Isafjordur,Iceland,IFJ,BIIS,66.058056,-23.135278,8,0,N,Atlantic/Reykjavik
15,15,16,Keflavik International Airport,Keflavik,Iceland,KEF,BIKF,63.985,-22.605556,171,0,N,Atlantic/Reykjavik
16,16,17,Patreksfjordur,Patreksfjordur,Iceland,PFJ,BIPA,65.555833,-23.965,11,0,N,Atlantic/Reykjavik
17,17,18,Reykjavik,Reykjavik,Iceland,RKV,BIRK,64.13,-21.940556,48,0,N,Atlantic/Reykjavik
18,18,19,Siglufjordur,Siglufjordur,Iceland,SIJ,BISI,66.133333,-18.916667,10,0,N,Atlantic/Reykjavik
19,19,20,Vestmannaeyjar,Vestmannaeyjar,Iceland,VEY,BIVM,63.424303,-20.278875,326,0,N,Atlantic/Reykjavik
20,20,21,Sault Ste Marie,Sault Sainte Marie,Canada,YAM,CYAM,46.485001,-84.509445,630,-5,A,America/Toronto
21,21,22,Winnipeg St Andrews,Winnipeg,Canada,YAV,CYAV,50.056389,-97.0325,760,-6,A,America/Winnipeg
22,22,23,Shearwater,Halifax,Canada,YAW,CYAW,44.639721,-63.499444,167,-4,A,America/Halifax
23,23,24,St Anthony,St. Anthony,Canada,YAY,CYAY,51.391944,-56.083056,108,-3.5,A,America/St_Johns
24,24,25,Tofino,Tofino,Canada,YAZ,CYAZ,49.082222,-125.7725,80,-8,A,America/Vancouver
25,25,26,Kugaaruk,Pelly Bay,Canada,YBB,CYBB,68.534444,-89.808056,56,-7,A,America/Edmonton
26,26,27,Baie Comeau,Baie Comeau,Canada,YBC,CYBC,49.1325,-68.204444,71,-5,A,America/Toronto
27,27,28,Bagotville,Bagotville,Canada,YBG,CYBG,48.330555,-70.996391,522,-5,A,America/Toronto
28,28,29,Baker Lake,Baker Lake,Canada,YBK,CYBK,64.298889,-96.077778,59,-6,A,America/Winnipeg
29,29,30,Campbell River,Campbell River,Canada,YBL,CYBL,49.950832,-125.270833,346,-8,A,America/Vancouver
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077,8077,9512,Port of Seattle,Seattle,United States,None,PSEA,47.609178,-122.350605,0,-8,A,America/Los_Angeles
8078,8078,9513,Ferry Terminal,Whittier,United States,None,WHIT,60.776566,-148.683367,0,-9,A,America/Anchorage
8079,8079,9514,Ferry Terminal,Valdez,United States,None,VLDZ,61.123976,-146.365309,0,-9,A,America/Anchorage
8080,8080,9515,Gare Routiere,Saint-Louis,Reunion,None,STLS,-21.289604,55.407269,103,4,E,Indian/Reunion
8081,8081,9516,Bus Stop,La Riviere,Reunion,None,LRIV,-21.272574,55.437706,190,4,E,Indian/Reunion
8082,8082,9517,Bus Stop,Cilaos,Reunion,None,CILS,-21.135518,55.472087,4000,4,E,Indian/Reunion
8083,8083,9518,Bus Stop,Hell-Bourg,Reunion,None,HLBG,-21.06402,55.518453,3000,4,E,Indian/Reunion
8084,8084,9519,Bus Stop,Salazie,Reunion,None,SLZI,-21.027485,55.538955,3000,4,E,Indian/Reunion
8085,8085,9520,Gare,St Andre,Reunion,None,ANDR,-20.963272,55.652508,100,4,E,Indian/Reunion
8086,8086,9521,L'Ocean Bus Terminal,Saint Denis,Reunion,None,SDNS,-20.877683,55.457393,0,4,E,Indian/Reunion
8087,8087,9522,Gare Routiere,Saint Pierre,Reunion,None,STPR,-21.33424,55.471331,0,4,E,Indian/Reunion
8088,8088,9523,Baie Ste Anne,Praslin,Seychelles,None,PLIN,-4.347119,55.765688,0,4,N,Indian/Mahe
8089,8089,9524,La Passe,La Digue,Seychelles,None,LADG,-4.347969,55.829069,0,4,N,Indian/Mahe
8090,8090,9525,Ferry Dock,Bainbridge Island,United States,None,BAIN,47.622237,-122.509362,0,-8,A,America/Los_Angeles
8091,8091,9526,Bus,Phnom Penh,Cambodia,None,PNMP,11.561716,104.914276,0,7,N,Asia/Phnom_Penh
8092,8092,9527,Bus,Siem Reap,Cambodia,None,SMRP,13.361002,103.859543,0,7,N,Asia/Phnom_Penh
8093,8093,9528,Bus,Sihanoukville,Cambodia,None,SNKV,10.60722,103.524886,0,7,N,Asia/Phnom_Penh
8094,8094,9529,Bus,Kampot,Cambodia,None,KMPT,10.614922,104.177724,0,7,N,Asia/Phnom_Penh
8095,8095,9530,Bus,Kep,Cambodia,None,KEPC,10.480174,104.294228,0,7,N,Asia/Phnom_Penh
8096,8096,9531,Main Station,Taipei,Taiwan,None,TPEI,25.046176,121.517532,0,8,N,Asia/Taipei
8097,8097,9532,Prominent Hill,Prominent Hill,Australia,PXH,YPMH,-29.716667,135.521667,734,9.5,O,Australia/Adelaide
8098,8098,9533,Chatsworth Station,Chatsworth,United States,CWT,\N,34.256944,-118.598889,978,-8,A,America/Los_Angeles
8099,8099,9534,Algerciras Port,Algerciras,Spain,None,\N,36.136,-5.435,0,1,E,Europe/Madrid
8100,8100,9535,Ganges Water Aerodrome,Ganges,Canada,YGG,\N,48.85,-123.5,0,-8,A,America/Vancouver
8101,8101,9536,Pender Harbour Water Aerodrome,Pender Harbour,Canada,YPT,\N,49.616667,-124.016667,0,-8,A,America/Vancouver
8102,8102,9537,Mansons Landing Water Aerodrome,Mansons Landing,Canada,YMU,\N,50.066667,-124.983333,0,-8,A,America/Vancouver
8103,8103,9538,Port McNeill Airport,Port McNeill,Canada,YMP,\N,50.575556,-127.028611,225,-8,A,America/Vancouver
8104,8104,9539,Sullivan Bay Water Aerodrome,Sullivan Bay,Canada,YTG,\N,50.883333,-126.833333,0,-8,A,America/Vancouver
8105,8105,9540,Deer Harbor Seaplane,Deer Harbor,United States,DHB,\N,48.618397,-123.00596,0,-8,A,America/Los_Angeles
8106,8106,9541,San Diego Old Town Transit Center,San Diego,United States,OLT,\N,32.7552,-117.1995,0,-8,A,America/Los_Angeles

In [13]:
df_routes

,index,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
0,0,2B,410,AER,2965,KZN,2990,None,0,CR2
1,1,2B,410,ASF,2966,KZN,2990,None,0,CR2
2,2,2B,410,ASF,2966,MRV,2962,None,0,CR2
3,3,2B,410,CEK,2968,KZN,2990,None,0,CR2
4,4,2B,410,CEK,2968,OVB,4078,None,0,CR2
5,5,2B,410,DME,4029,KZN,2990,None,0,CR2
6,6,2B,410,DME,4029,NBC,6969,None,0,CR2
7,7,2B,410,DME,4029,TGK,\N,None,0,CR2
8,8,2B,410,DME,4029,UUA,6160,None,0,CR2
9,9,2B,410,EGO,6156,KGD,2952,None,0,CR2
10,10,2B,410,EGO,6156,KZN,2990,None,0,CR2
11,11,2B,410,GYD,2922,NBC,6969,None,0,CR2
12,12,2B,410,KGD,2952,EGO,6156,None,0,CR2
13,13,2B,410,KZN,2990,AER,2965,None,0,CR2
14,14,2B,410,KZN,2990,ASF,2966,None,0,CR2
15,15,2B,410,KZN,2990,CEK,2968,None,0,CR2
16,16,2B,410,KZN,2990,DME,4029,None,0,CR2
17,17,2B,410,KZN,2990,EGO,6156,None,0,CR2
18,18,2B,410,KZN,2990,LED,2948,None,0,CR2
19,19,2B,410,KZN,2990,SVX,2975,None,0,CR2
20,20,2B,410,LED,2948,KZN,2990,None,0,CR2
21,21,2B,410,LED,2948,NBC,6969,None,0,CR2
22,22,2B,410,LED,2948,UUA,6160,None,0,CR2
23,23,2B,410,MRV,2962,ASF,2966,None,0,CR2
24,24,2B,410,NBC,6969,DME,4029,None,0,CR2
25,25,2B,410,NBC,6969,GYD,2922,None,0,CR2
26,26,2B,410,NBC,6969,LED,2948,None,0,CR2
27,27,2B,410,NBC,6969,SVX,2975,None,0,CR2
28,28,2B,410,NJC,2972,SVX,2975,None,0,CR2
29,29,2B,410,NJC,2972,UUA,6160,None,0,CR2
...,...,...,...,...,...,...,...,...,...,...
67633,67633,ZL,4178,SYD,3361,ABX,3333,None,0,SF3
67634,67634,ZL,4178,SYD,3361,ARM,4062,None,0,SF3
67635,67635,ZL,4178,SYD,3361,BHQ,6241,None,0,SF3
67636,67636,ZL,4178,SYD,3361,BHS,6249,None,0,SF3
67637,67637,ZL,4178,SYD,3361,BNK,4291,None,0,SF3
67638,67638,ZL,4178,SYD,3361,DBO,3358,None,0,SF3
67639,67639,ZL,4178,SYD,3361,GFF,6271,None,0,SF3
67640,67640,ZL,4178,SYD,3361,LSY,6287,None,0,SF3
67641,67641,ZL,4178,SYD,3361,MIM,6294,None,0,SF3
67642,67642,ZL,4178,SYD,3361,MQL,6298,None,0,SF3
67643,67643,ZL,4178,SYD,3361,MYA,6302,None,0,SF3
67644,67644,ZL,4178,SYD,3361,NRA,6307,None,0,SF3
67645,67645,ZL,4178,SYD,3361,NTL,4320,None,0,SF3
67646,67646,ZL,4178,SYD,3361,OAG,6793,None,0,SF3
67647,67647,ZL,4178,SYD,3361,PKE,6317,None,0,SF3
67648,67648,ZL,4178,SYD,3361,TRO,6794,None,0,SF3
67649,67649,ZL,4178,SYD,3361,WGA,3363,None,0,SF3
67650,67650,ZL,4178,TRO,6794,GFN,6792,None,0,SF3
67651,67651,ZL,4178,TRO,6794,SYD,3361,None,0,SF3
67652,67652,ZL,4178,TSV,3330,ISA,3324,None,0,SF3
67653,67653,ZL,4178,TSV,3330,WIN,6337,None,0,SF3
67654,67654,ZL,4178,WGA,3363,MEL,3339,None,0,SF3
67655,67655,ZL,4178,WGA,3363,SYD,3361,None,0,SF3
67656,67656,ZL,4178,WIN,6337,LRE,6289,None,0,SF3
67657,67657,ZL,4178,WIN,6337,TSV,3330,None,0,SF3
67658,67658,ZL,4178,WYA,6334,ADL,3341,None,0,SF3
67659,67659,ZM,19016,DME,4029,FRU,2912,None,0,734
67660,67660,ZM,19016,FRU,2912,DME,4029,None,0,734
67661,67661,ZM,19016,FRU,2912,OSS,2913,None,0,734
67662,67662,ZM,19016,OSS,2913,FRU,2912,None,0,734

In [15]:
!pip install openpyxl

Collecting openpyxl
  Downloading https://files.pythonhosted.org/packages/ba/06/b899c8867518df19e242d8cbc82d4ba210f5ffbeebb7704c695e687ab59c/openpyxl-2.6.2.tar.gz (173kB)
Collecting jdcal (from openpyxl)
  Downloading https://files.pythonhosted.org/packages/a0/38/dcf83532480f25284f3ef13f8ed63e03c58a65c9d3ba2a6a894ed9497207/jdcal-1.4-py2.py3-none-any.whl
Collecting et_xmlfile (from openpyxl)
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Building wheels for collected packages: openpyxl, et-xmlfile
  Building wheel for openpyxl (setup.py): started
  Building wheel for openpyxl (setup.py): finished with status 'done'
  Stored in directory: C:\Users\hogoo\AppData\Local\pip\Cache\wheels\82\cd\05\2e1db4b561fda743444f9573f2c5090a7b991200c92770dd7a
  Building wheel for et-xmlfile (setup.py): started
  Building wheel for et-xmlfile (setup.py): finished with status 'done'
  Stored in directory: C:\Users\hogoo\AppData\Local\pip\Cache\wheels\2a\77\35\0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
Successfully built openpyxl et-xmlfile
Installing collected packages: jdcal, et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.0.1 jdcal-1.4 openpyxl-2.6.2

In [16]:
!pip install XlsxWriter

Collecting XlsxWriter
  Downloading https://files.pythonhosted.org/packages/15/d0/73a90dd23b044f05ae758db51920f8f235ab4a6d8cc357d84743acc0099b/XlsxWriter-1.1.6-py2.py3-none-any.whl (139kB)
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-1.1.6

## pandas persistance

In [17]:
writer = pd.ExcelWriter('./data/df_routes.xlsx',engine='xlsxwriter')
df_routes.to_excel(writer, sheet_name='Sheet1')

## pickle
#### to_pickle, read_pickle 사용

In [18]:
df_routes.to_pickle('./data/df_routes.pickle')

In [19]:
df_routes_pickle = pd.read_pickle('./data/df_routes.pickle')
df_routes_pickle.head()

,index,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
0,0,2B,410,AER,2965,KZN,2990,None,0,CR2
1,1,2B,410,ASF,2966,KZN,2990,None,0,CR2
2,2,2B,410,ASF,2966,MRV,2962,None,0,CR2
3,3,2B,410,CEK,2968,KZN,2990,None,0,CR2
4,4,2B,410,CEK,2968,OVB,4078,None,0,CR2