In [1]:
import pandas as pd

In [26]:
weather = pd.read_csv("./data/data/weather.txt",sep='\t')

In [18]:
tb = pd.read_csv("./data/data/data-zillow.csv")

In [19]:
import sys

In [20]:
sys.stdout.encoding

'UTF-8'

In [21]:
tb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10830 entries, 0 to 10829
Data columns (total 8 columns):
Date          10830 non-null object
RegionID      10830 non-null int64
RegionName    10830 non-null object
State         10830 non-null object
Metro         10256 non-null object
County        10830 non-null object
SizeRank      10830 non-null int64
Zhvi          10830 non-null int64
dtypes: int64(3), object(5)
memory usage: 677.0+ KB

In [25]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 1 columns):
id	"year"	"month"	"element"	"d1"	"d2"	"d3"	"d4"	"d5"	"d6"	"d7"	"d8"	"d9"	"d10"	"d11"	"d12"	"d13"	"d14"	"d15"	"d16"	"d17"	"d18"	"d19"	"d20"	"d21"	"d22"	"d23"	"d24"	"d25"	"d26"	"d27"	"d28"	"d29"	"d30"	"d31"    22 non-null object
dtypes: object(1)
memory usage: 256.0+ bytes

In [30]:
weather.melt(id_vars=['id','year','month','element'])

              id  year  month element variable  value
0    MX000017004  2010      1    TMAX       d1    NaN
1    MX000017004  2010      1    TMIN       d1    NaN
2    MX000017004  2010      2    TMAX       d1    NaN
3    MX000017004  2010      2    TMIN       d1    NaN
4    MX000017004  2010      3    TMAX       d1    NaN
5    MX000017004  2010      3    TMIN       d1    NaN
6    MX000017004  2010      4    TMAX       d1    NaN
7    MX000017004  2010      4    TMIN       d1    NaN
8    MX000017004  2010      5    TMAX       d1    NaN
9    MX000017004  2010      5    TMIN       d1    NaN
10   MX000017004  2010      6    TMAX       d1    NaN
11   MX000017004  2010      6    TMIN       d1    NaN
12   MX000017004  2010      7    TMAX       d1    NaN
13   MX000017004  2010      7    TMIN       d1    NaN
14   MX000017004  2010      8    TMAX       d1    NaN
15   MX000017004  2010      8    TMIN       d1    NaN
16   MX000017004  2010     10    TMAX       d1    NaN
17   MX000017004  2010     10    TMIN       d1    NaN
18   MX000017004  2010     11    TMAX       d1    NaN
19   MX000017004  2010     11    TMIN       d1    NaN
20   MX000017004  2010     12    TMAX       d1  299.0
21   MX000017004  2010     12    TMIN       d1  138.0
22   MX000017004  2010      1    TMAX       d2    NaN
23   MX000017004  2010      1    TMIN       d2    NaN
24   MX000017004  2010      2    TMAX       d2  273.0
25   MX000017004  2010      2    TMIN       d2  144.0
26   MX000017004  2010      3    TMAX       d2    NaN
27   MX000017004  2010      3    TMIN       d2    NaN
28   MX000017004  2010      4    TMAX       d2    NaN
29   MX000017004  2010      4    TMIN       d2    NaN
..           ...   ...    ...     ...      ...    ...
652  MX000017004  2010      8    TMAX      d30    NaN
653  MX000017004  2010      8    TMIN      d30    NaN
654  MX000017004  2010     10    TMAX      d30    NaN
655  MX000017004  2010     10    TMIN      d30    NaN
656  MX000017004  2010     11    TMAX      d30    NaN
657  MX000017004  2010     11    TMIN      d30    NaN
658  MX000017004  2010     12    TMAX      d30    NaN
659  MX000017004  2010     12    TMIN      d30    NaN
660  MX000017004  2010      1    TMAX      d31    NaN
661  MX000017004  2010      1    TMIN      d31    NaN
662  MX000017004  2010      2    TMAX      d31    NaN
663  MX000017004  2010      2    TMIN      d31    NaN
664  MX000017004  2010      3    TMAX      d31    NaN
665  MX000017004  2010      3    TMIN      d31    NaN
666  MX000017004  2010      4    TMAX      d31    NaN
667  MX000017004  2010      4    TMIN      d31    NaN
668  MX000017004  2010      5    TMAX      d31    NaN
669  MX000017004  2010      5    TMIN      d31    NaN
670  MX000017004  2010      6    TMAX      d31    NaN
671  MX000017004  2010      6    TMIN      d31    NaN
672  MX000017004  2010      7    TMAX      d31    NaN
673  MX000017004  2010      7    TMIN      d31    NaN
674  MX000017004  2010      8    TMAX      d31  254.0
675  MX000017004  2010      8    TMIN      d31  154.0
676  MX000017004  2010     10    TMAX      d31    NaN
677  MX000017004  2010     10    TMIN      d31    NaN
678  MX000017004  2010     11    TMAX      d31    NaN
679  MX000017004  2010     11    TMIN      d31    NaN
680  MX000017004  2010     12    TMAX      d31    NaN
681  MX000017004  2010     12    TMIN      d31    NaN

[682 rows x 6 columns]

In [29]:
weather.columns

Index(['id', 'year', 'month', 'element', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6',
       'd7', 'd8', 'd9', 'd10', 'd11', 'd12', 'd13', 'd14', 'd15', 'd16',
       'd17', 'd18', 'd19', 'd20', 'd21', 'd22', 'd23', 'd24', 'd25', 'd26',
       'd27', 'd28', 'd29', 'd30', 'd31'],
      dtype='object')

In [27]:
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX000017004,2010,1,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN
1,MX000017004,2010,1,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,NaN
2,MX000017004,2010,2,TMAX,NaN,273.0,241.0,NaN,NaN,NaN,...,NaN,299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX000017004,2010,2,TMIN,NaN,144.0,144.0,NaN,NaN,NaN,...,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX000017004,2010,3,TMAX,NaN,NaN,NaN,NaN,321.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX000017004,2010,3,TMIN,NaN,NaN,NaN,NaN,142.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX000017004,2010,4,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,363.0,NaN,NaN,NaN,NaN
7,MX000017004,2010,4,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN
8,MX000017004,2010,5,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,332.0,NaN,NaN,NaN,NaN
9,MX000017004,2010,5,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,182.0,NaN,NaN,NaN,NaN
10,MX000017004,2010,6,TMAX,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,NaN,NaN
11,MX000017004,2010,6,TMIN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN
12,MX000017004,2010,7,TMAX,NaN,NaN,286.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX000017004,2010,7,TMIN,NaN,NaN,175.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX000017004,2010,8,TMAX,NaN,NaN,NaN,NaN,296.0,NaN,...,NaN,264.0,NaN,297.0,NaN,NaN,NaN,280.0,NaN,254.0
15,MX000017004,2010,8,TMIN,NaN,NaN,NaN,NaN,158.0,NaN,...,NaN,150.0,NaN,156.0,NaN,NaN,NaN,153.0,NaN,154.0
16,MX000017004,2010,10,TMAX,NaN,NaN,NaN,NaN,270.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,312.0,NaN,NaN,NaN
17,MX000017004,2010,10,TMIN,NaN,NaN,NaN,NaN,140.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN
18,MX000017004,2010,11,TMAX,NaN,313.0,NaN,272.0,263.0,NaN,...,NaN,NaN,NaN,NaN,281.0,277.0,NaN,NaN,NaN,NaN
19,MX000017004,2010,11,TMIN,NaN,163.0,NaN,120.0,79.0,NaN,...,NaN,NaN,NaN,NaN,121.0,142.0,NaN,NaN,NaN,NaN
20,MX000017004,2010,12,TMAX,299.0,NaN,NaN,NaN,NaN,278.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX000017004,2010,12,TMIN,138.0,NaN,NaN,NaN,NaN,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN